
package base_de_donne;

import Application.BDD;
import Application.parameter;
import application.ResultSetTableModel;
import java.sql.*;
import javax.swing.JOptionPane;


public class recu extends javax.swing.JFrame {

  ResultSet rs ;
    BDD db ;
    public recu() {
            db = new BDD(new parameter().HOST_DB, new parameter().USERNAME_DB,
            new parameter().PASSWORD_DB, new parameter().IPHOST, new parameter().PORT);
        initComponents();
        importer();
        
        date();
    }

    
    public void importer() {
       String colon[] = {"num_facture","code_produit","reference","prix_vente","stock_sortie","subtotal"};
        //rs = db.fcSelectCommand(colon, "vente", "num_facture='" +Cachier.txt_fac.getText() + "'");
        rs = db.fcSelectCommand(colon, "vente", "num_facture='" + "'");
        tbleImp.setModel(new ResultSetTableModel(rs));
        //lbltot.setText(Cachier.lbltot2.getText());
        //lblcas.setText(Cachier.txt_cas.getText());
        payapres();
    }
    
    


    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblh = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbleImp = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblpay = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbltot = new javax.swing.JLabel();
        lblcas = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbld = new javax.swing.JLabel();
        lblhe = new javax.swing.JLabel();

        lblh.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("RECU");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 10, 110, 70);

        tbleImp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "num_facture", "code_produit", "reference", "prix_vente", "stock_sortie", "subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbleImp);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 130, 640, 90);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 330, 120, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("imprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 260, 120, 50);

        lblpay.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblpay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpay.setText("XX");
        lblpay.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblpay);
        lblpay.setBounds(420, 390, 130, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Cash :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 330, 80, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Payé aprés :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 380, 120, 40);

        lbltot.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbltot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltot.setText("XX");
        jPanel1.add(lbltot);
        lbltot.setBounds(410, 270, 110, 29);

        lblcas.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblcas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcas.setText("XX");
        jPanel1.add(lblcas);
        lblcas.setBounds(420, 330, 100, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Total :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(290, 270, 80, 40);

        lbld.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(lbld);
        lbld.setBounds(20, 80, 320, 40);

        lblhe.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(lblhe);
        lblhe.setBounds(360, 80, 320, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Cachier p = new Cachier();
p.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.printComponents(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    
      public void date(){
         
          // lblhe.setText(Cachier.lbl1.getText());
        //lbld.setText(Cachier.lbl2.getText());
    }
    
    //
      
          public void payapres() {
        int a = Integer.parseInt(lbld.getText());
        int b = Integer.parseInt(lblhe.getText());
        int c = b - a;
        lblpay.setText(Integer.toString(c));
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcas;
    public static javax.swing.JLabel lbld;
    private javax.swing.JLabel lblh;
    public static javax.swing.JLabel lblhe;
    private javax.swing.JLabel lblpay;
    private javax.swing.JLabel lbltot;
    public javax.swing.JTable tbleImp;
    // End of variables declaration//GEN-END:variables

}
